base_url = "https://jayrovacsek.github.io/blog"
theme = "after-dark"
compile_sass = true
build_search_index = true
hard_link_static = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true

[extra]
after_dark_menu = [
    {url = "$BASE_URL", name = "home"},
    {url = "$BASE_URL/tags", name = "tags"},
]
