concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Publish Site
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.1
      - name: build
        run: zola build
      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

on:
  workflow_run:
    workflows: ["checks"]
    branches: [main]
    types:
      - completed

name: deploy
